In [8]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [9]:
 data = pd.read_csv('/home/karthi_krish/CSV_files/Machine_learning_course/50_Startups.csv')

In [10]:
X = data.iloc[:,:4].values
Y = data.iloc[:,4:].values

In [11]:
from sklearn.impute import SimpleImputer

In [12]:
imputer_num = SimpleImputer(missing_values = np.nan,strategy = 'mean')
imputer_string = SimpleImputer(missing_values = np.nan,strategy = 'most_frequent')
imputer_num = imputer_num.fit(X[:,:3])
imputer_string = imputer_string.fit(X[:,3:])

In [13]:
X[:,:3] = imputer_num.transform(X[:,:3])
X[:,3:] = imputer_string.transform(X[:,3:])

In [83]:


from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.25,random_state = 0)

In [14]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [15]:
ct = ColumnTransformer([('one_hot_encoder',OneHotEncoder(categories = 'auto'),[3])],remainder = 'passthrough')

In [16]:
ct = ct.fit(X)
X = ct.transform(X)

In [87]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.25,random_state = 0)

In [17]:
imputer = SimpleImputer(missing_values = np.nan,strategy = 'mean')
imputer = imputer.fit(Y)
Y = imputer.transform(Y)


In [18]:
X = X[:,1:]
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.25,random_state = 0)
from sklearn.linear_model import LinearRegression

In [19]:
regressor = LinearRegression()
regressor = regressor.fit(X_train,Y_train)

In [20]:
y_pred = regressor.predict(X_test)


In [21]:
X

array([[0.0, 1.0, 165349.2, 136897.8, 471784.1],
       [0.0, 0.0, 162597.7, 151377.59, 443898.53],
       [1.0, 0.0, 153441.51, 101145.55, 407934.54],
       [0.0, 1.0, 144372.41, 118671.85, 383199.62],
       [1.0, 0.0, 142107.34, 91391.77, 366168.42],
       [0.0, 1.0, 131876.9, 99814.71, 362861.36],
       [0.0, 0.0, 134615.46, 147198.87, 127716.82],
       [1.0, 0.0, 130298.13, 145530.06, 323876.68],
       [0.0, 1.0, 120542.52, 148718.95, 311613.29],
       [0.0, 0.0, 123334.88, 108679.17, 304981.62],
       [1.0, 0.0, 101913.08, 110594.11, 229160.95],
       [0.0, 0.0, 100671.96, 91790.61, 249744.55],
       [1.0, 0.0, 93863.75, 127320.38, 249839.44],
       [0.0, 0.0, 91992.39, 135495.07, 252664.93],
       [1.0, 0.0, 119943.24, 156547.42, 256512.92],
       [0.0, 1.0, 114523.61, 122616.84, 261776.23],
       [0.0, 0.0, 78013.11, 121597.55, 264346.06],
       [0.0, 1.0, 94657.16, 145077.58, 282574.31],
       [1.0, 0.0, 91749.16, 114175.79, 294919.57],
       [0.0, 1.0, 86419.7

In [22]:
X = np.append(arr = np.ones((51,1)).astype(int),values = X,axis = 1)

In [23]:
X.shape


(51, 6)

In [24]:
X

array([[1, 0.0, 1.0, 165349.2, 136897.8, 471784.1],
       [1, 0.0, 0.0, 162597.7, 151377.59, 443898.53],
       [1, 1.0, 0.0, 153441.51, 101145.55, 407934.54],
       [1, 0.0, 1.0, 144372.41, 118671.85, 383199.62],
       [1, 1.0, 0.0, 142107.34, 91391.77, 366168.42],
       [1, 0.0, 1.0, 131876.9, 99814.71, 362861.36],
       [1, 0.0, 0.0, 134615.46, 147198.87, 127716.82],
       [1, 1.0, 0.0, 130298.13, 145530.06, 323876.68],
       [1, 0.0, 1.0, 120542.52, 148718.95, 311613.29],
       [1, 0.0, 0.0, 123334.88, 108679.17, 304981.62],
       [1, 1.0, 0.0, 101913.08, 110594.11, 229160.95],
       [1, 0.0, 0.0, 100671.96, 91790.61, 249744.55],
       [1, 1.0, 0.0, 93863.75, 127320.38, 249839.44],
       [1, 0.0, 0.0, 91992.39, 135495.07, 252664.93],
       [1, 1.0, 0.0, 119943.24, 156547.42, 256512.92],
       [1, 0.0, 1.0, 114523.61, 122616.84, 261776.23],
       [1, 0.0, 0.0, 78013.11, 121597.55, 264346.06],
       [1, 0.0, 1.0, 94657.16, 145077.58, 282574.31],
       [1, 1.0, 0.0, 9

In [25]:
help(np.hstack)

Help on function hstack in module numpy:

hstack(tup)
    Stack arrays in sequence horizontally (column wise).
    
    This is equivalent to concatenation along the second axis, except for 1-D
    arrays where it concatenates along the first axis. Rebuilds arrays divided
    by `hsplit`.
    
    This function makes most sense for arrays with up to 3 dimensions. For
    instance, for pixel-data with a height (first axis), width (second axis),
    and r/g/b channels (third axis). The functions `concatenate`, `stack` and
    `block` provide more general stacking and concatenation operations.
    
    Parameters
    ----------
    tup : sequence of ndarrays
        The arrays must have the same shape along all but the second axis,
        except 1-D arrays which can be any length.
    
    Returns
    -------
    stacked : ndarray
        The array formed by stacking the given arrays.
    
    See Also
    --------
    stack : Join a sequence of arrays along a new axis.
    vstack : Stac

In [26]:
np.hstack((np.ones((51,1), dtype=int),X))

array([[1, 1, 0.0, 1.0, 165349.2, 136897.8, 471784.1],
       [1, 1, 0.0, 0.0, 162597.7, 151377.59, 443898.53],
       [1, 1, 1.0, 0.0, 153441.51, 101145.55, 407934.54],
       [1, 1, 0.0, 1.0, 144372.41, 118671.85, 383199.62],
       [1, 1, 1.0, 0.0, 142107.34, 91391.77, 366168.42],
       [1, 1, 0.0, 1.0, 131876.9, 99814.71, 362861.36],
       [1, 1, 0.0, 0.0, 134615.46, 147198.87, 127716.82],
       [1, 1, 1.0, 0.0, 130298.13, 145530.06, 323876.68],
       [1, 1, 0.0, 1.0, 120542.52, 148718.95, 311613.29],
       [1, 1, 0.0, 0.0, 123334.88, 108679.17, 304981.62],
       [1, 1, 1.0, 0.0, 101913.08, 110594.11, 229160.95],
       [1, 1, 0.0, 0.0, 100671.96, 91790.61, 249744.55],
       [1, 1, 1.0, 0.0, 93863.75, 127320.38, 249839.44],
       [1, 1, 0.0, 0.0, 91992.39, 135495.07, 252664.93],
       [1, 1, 1.0, 0.0, 119943.24, 156547.42, 256512.92],
       [1, 1, 0.0, 1.0, 114523.61, 122616.84, 261776.23],
       [1, 1, 0.0, 0.0, 78013.11, 121597.55, 264346.06],
       [1, 1, 0.0, 1.0, 9

In [36]:
X = X.astype(float)
X_opt = X[:,[0,1,2,3,4,5]]
import statsmodels.formula.api as sm
regressor_OLS = sm.OLS(endog = Y,exog = X_opt).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.614
Model:                            OLS   Adj. R-squared:                  0.572
Method:                 Least Squares   F-statistic:                     14.34
Date:                Tue, 07 May 2019   Prob (F-statistic):           2.13e-08
Time:                        15:49:44   Log-Likelihood:                -587.86
No. Observations:                  51   AIC:                             1188.
Df Residuals:                      45   BIC:                             1199.
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const        1.87e+04   1.84e+04      1.017      0.314   -1.83e+04    5.57e+04
x1         -1131.2626   9324.689     -0.121      0.904   -1.99e+04    1.76e+04
x2          4411.2958   8980.922      0.491      0.626   -1.37e+04    2.25e+04
x3             0.0029      0.007      0.392      0.697      -0.012       0.018
x4             0.3224      0.133      2.418      0.020       0.054       0.591
x5             0.2495      0.031      7.939      0.000       0.186       0.313
==============================================================================
Omnibus:                        5.833   Durbin-Watson:                   1.323
Prob(Omnibus):                  0.054   Jarque-Bera (JB):                5.684
Skew:                          -0.442   Prob(JB):                       0.0583
Kurtosis:                       4.376   Cond. No.                     2.69e+06
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.69e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [55]:
import statsmodels.formula.api as sm
def backwardelimination(x,y,sl):
    num = len(x[0])
    for i in range(0,num):
        regressor_OLS = sm.OLS(endog = y,exog = x).fit()
        maxvar = max(regressor_OLS.pvalues)
        if maxvar >sl:
            for j in range(0,num-i):
                if regressor_OLS.pvalues[j] == maxvar:
                    x = np.delete(x,j,axis = 1)
    regressor_OLS.summary()
    return x

In [56]:
X_opt = X[:,[0,1,2,3,4,5]]
regressor_OLS = sm.OLS(endog = Y,exog = X_opt).fit()
max(regressor_OLS.pvalues)

0.9039784370311645

In [57]:
sl = 0.05
print(backwardelimination(X,Y,sl))

[[136897.8    471784.1   ]
 [151377.59   443898.53  ]
 [101145.55   407934.54  ]
 [118671.85   383199.62  ]
 [ 91391.77   366168.42  ]
 [ 99814.71   362861.36  ]
 [147198.87   127716.82  ]
 [145530.06   323876.68  ]
 [148718.95   311613.29  ]
 [108679.17   304981.62  ]
 [110594.11   229160.95  ]
 [ 91790.61   249744.55  ]
 [127320.38   249839.44  ]
 [135495.07   252664.93  ]
 [156547.42   256512.92  ]
 [122616.84   261776.23  ]
 [121597.55   264346.06  ]
 [145077.58   282574.31  ]
 [114175.79   294919.57  ]
 [153514.11        0.    ]
 [113867.3    298664.47  ]
 [153773.43   299737.29  ]
 [122782.75   303319.26  ]
 [105751.03   304768.73  ]
 [ 99281.34   140574.81  ]
 [139553.16   137962.62  ]
 [144135.98   134050.07  ]
 [127864.55   353183.81  ]
 [182645.56   118148.2   ]
 [153032.06   107138.38  ]
 [115641.28    91131.24  ]
 [152701.92    88218.23  ]
 [129219.61    46085.25  ]
 [103057.49   214634.81  ]
 [157693.92   210797.67  ]
 [ 85047.44   205517.64  ]
 [127056.21   201126.82  ]
 

In [58]:
regressor_OLS.predict(X_opt)

array([185448.48284419, 178739.80244003, 152412.02301052, 157407.22847647,
       138812.64080724, 146216.00467073,  98417.1031167 , 145681.16215528,
       149163.52638751, 130195.77066356, 110700.73246683, 110901.68722315,
       121229.98734657, 125696.54934449, 132394.63588515, 128294.6321346 ,
       124089.61679139, 140668.26164701, 128234.10684468,  72856.27316844,
       130155.22012283, 147707.18293796, 133053.41574496, 127904.81167149,
        90419.27616997,  98304.80861562,  97705.95077775, 152671.22343652,
       106127.56785277,  99373.4979985 ,  77770.56725994,  94533.07028767,
        72044.03923494, 104511.01024224, 122274.60995083, 101944.14315188,
       108800.17207799,  84522.72500603,  90657.47127239,  89230.25935029,
       100118.59457576,  85998.21272542,  86708.66690183,  73090.75562458,
        75744.62153148,  63615.88345705, 129047.39313074,  62361.59311487,
        39792.67633501,  67686.67543287, 121208.27578533])